/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codigo;

import static codigo.Tokens.Cadena;
import static codigo.Tokens.Comillas;
import static codigo.Tokens.Corchete_a;
import static codigo.Tokens.Corchete_c;
import static codigo.Tokens.Division;
import static codigo.Tokens.Do;
import static codigo.Tokens.ERROR;
import static codigo.Tokens.Else;
import static codigo.Tokens.For;
import static codigo.Tokens.Identificador;
import static codigo.Tokens.If;
import static codigo.Tokens.Igual;
import static codigo.Tokens.Linea;
import static codigo.Tokens.Llave_a;
import static codigo.Tokens.Llave_c;
import static codigo.Tokens.Main;
import static codigo.Tokens.Multiplicacion;
import static codigo.Tokens.Numero;
import static codigo.Tokens.Op_atribucion;
import static codigo.Tokens.Op_booleano;
import static codigo.Tokens.Op_incremento;
import static codigo.Tokens.Op_logico;
import static codigo.Tokens.Op_relacional;
import static codigo.Tokens.P_coma;
import static codigo.Tokens.Parentesis_a;
import static codigo.Tokens.Parentesis_c;
import static codigo.Tokens.Resta;
import static codigo.Tokens.Suma;
import static codigo.Tokens.T_dato;
import static codigo.Tokens.While;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.lang.System.Logger;
import java.util.logging.Level;

/**
 *
 * @author Abisai
 */
public class UIanalizador extends javax.swing.JFrame {

    /**
     * Creates new form UIanalizador
     */
    public UIanalizador() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDatos = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAnalizador = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTextArea2.setBackground(new java.awt.Color(206, 206, 214));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));

        txtDatos.setBackground(new java.awt.Color(206, 206, 214));
        txtDatos.setColumns(20);
        txtDatos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDatos.setForeground(new java.awt.Color(0, 0, 0));
        txtDatos.setRows(5);
        jScrollPane1.setViewportView(txtDatos);

        txtAnalizador.setBackground(new java.awt.Color(206, 206, 214));
        txtAnalizador.setColumns(20);
        txtAnalizador.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtAnalizador.setForeground(new java.awt.Color(0, 0, 0));
        txtAnalizador.setRows(5);
        jScrollPane3.setViewportView(txtAnalizador);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Ingresar Datos");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Analizador Lexico");

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Analizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(447, 447, 447)
                        .addComponent(jButton1)))
                .addGap(68, 68, 68))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        File archivo = new File("Archivo.txt");
        PrintWriter escribir;
        try {
            escribir = new PrintWriter(archivo);
            escribir.print(txtDatos.getText());
            escribir.close();

        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIanalizador.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            int cont = 1;
            Reader lector = new BufferedReader(new FileReader("archivo.txt"));
            Lexer lexer = new Lexer(lector);
            String resultado = "LINEA " + cont + "\t\tSIMBOLO\n";
            while (true) {
                Tokens tokens = lexer.yylex();
                if (tokens == null) {
                    resultado += "FIN";
                    txtAnalizador.setText(resultado);
                    return;

                }
                switch (tokens) {
                case Linea:
                    cont++;
                    resultado += String.format("LINEA %-5d\n", cont);
                    break;
                case Comillas:
                    resultado += String.format("  <Comillas>\t\t%s\n", lexer.lexeme);
                    break;
                case Cadena:
                    resultado += String.format("  <Tipo de dato>\t%s\n", lexer.lexeme);
                    break;
                case T_dato:
                    resultado += String.format("  <Tipo de dato>\t%s\n", lexer.lexeme);
                    break;
                case If:
                    resultado += String.format("  <Reservada if>\t%s\n", lexer.lexeme);
                    break;
                case Else:
                    resultado += String.format("  <Reservada else>\t%s\n", lexer.lexeme);
                    break;
                case Do:
                    resultado += String.format("  <Reservada do>\t%s\n", lexer.lexeme);
                    break;
                case While:
                    resultado += String.format("  <Reservada while>\t%s\n", lexer.lexeme);
                    break;
                case For:
                    resultado += String.format("  <Reservada for>\t%s\n", lexer.lexeme);
                    break;
                case Igual:
                    resultado += String.format("  <Operador igual>\t%s\n", lexer.lexeme);
                    break;
                case Suma:
                    resultado += String.format("  <Operador suma>\t%s\n", lexer.lexeme);
                    break;
                case Resta:
                    resultado += String.format("  <Operador resta>\t%s\n", lexer.lexeme);
                    break;
                case Multiplicacion:
                    resultado += String.format("  <Operador multiplicacion>\t%s\n", lexer.lexeme);
                    break;
                case Division:
                    resultado += String.format("  <Operador division>\t%s\n", lexer.lexeme);
                    break;
                case Op_logico:
                    resultado += String.format("  <Operador logico>\t%s\n", lexer.lexeme);
                    break;
                case Op_incremento:
                    resultado += String.format("  <Operador incremento>\t%s\n", lexer.lexeme);
                    break;
                case Op_relacional:
                    resultado += String.format("  <Operador relacional>\t%s\n", lexer.lexeme);
                    break;
                case Op_atribucion:
                    resultado += String.format("  <Operador atribucion>\t%s\n", lexer.lexeme);
                    break;
                case Op_booleano:
                    resultado += String.format("  <Operador booleano>\t%s\n", lexer.lexeme);
                    break;
                case Parentesis_a:
                    resultado += String.format("  <Parentesis de apertura>\t%s\n", lexer.lexeme);
                    break;
                case Parentesis_c:
                    resultado += String.format("  <Parentesis de cierre>\t%s\n", lexer.lexeme);
                    break;
                case Llave_a:
                    resultado += String.format("  <Llave de apertura>\t%s\n", lexer.lexeme);
                    break;
                case Llave_c:
                    resultado += String.format("  <Llave de cierre>\t%s\n", lexer.lexeme);
                    break;
                case Corchete_a:
                    resultado += String.format("  <Corchete de apertura>\t%s\n", lexer.lexeme);
                    break;
                case Corchete_c:
                    resultado += String.format("  <Corchete de cierre>\t%s\n", lexer.lexeme);
                    break;
                case Main:
                    resultado += String.format("  <Reservada main>\t%s\n", lexer.lexeme);
                    break;
                case P_coma:
                    resultado += String.format("  <Punto y coma>\t%s\n", lexer.lexeme);
                    break;
                case Identificador:
                    resultado += String.format("  <Identificador>\t%s\n", lexer.lexeme);
                    break;
                case Numero:
                    resultado += String.format("  <Numero>\t\t%s\n", lexer.lexeme);
                    break;
                case ERROR:
                    resultado += "  <Simbolo no definido>\n";
                    break;
                default:
                    resultado += String.format("  <%s>\n", lexer.lexeme);
                    break;
            }
        
            }
        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIanalizador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(UIanalizador.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIanalizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIanalizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIanalizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIanalizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIanalizador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea txtAnalizador;
    private javax.swing.JTextArea txtDatos;
    // End of variables declaration//GEN-END:variables
}
